name: Workflow 3
on:
  workflow_run:
    workflows: ["Workflow 2"]
    types:
      - completed
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "hello from Workflow 3"
